# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TABRWKV',
                'doc_host': 'https://robeson1010.github.io',
                'git_url': 'https://github.com/robeson1010/TABRWKV',
                'lib_path': 'TABRWKV'},
  'syms': {'TABRWKV.core': {'TABRWKV.core.foo': ('core.html#foo', 'TABRWKV/core.py')}}}
